Repository HippieStation/space-station-14, pull requests merged in 2023-04, with the labels that each got.

#20 fixes my fucky wucky
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: No C#

#23 adds new traitor gloves
  Resources/Locale/en-US/store/uplink-catalog.ftl
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
Labels: No C#

#29 Revert "Adds a peculiar plushie"
  Resources/Audio/Items/Toys/floyd1.ogg
  Resources/Audio/Items/Toys/floyd2.ogg
  Resources/Audio/Items/Toys/floyd3.ogg
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/SoundCollections/floyd_plush.yml
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/plushie_floyd.png
Labels: Changes: Sprites, No C#

#31 Revert "adds new traitor gloves"
  Resources/Locale/en-US/store/uplink-catalog.ftl
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
Labels: No C#

#36 Revert 16 cheackraze wiznerd
  Content.Server/GameTicking/Rules/Components/WizardComponent.cs
  Content.Server/GameTicking/Rules/Components/WizardSpawnerComponent.cs
  Content.Server/GameTicking/Rules/Configurations/WizardRuleConfiguration.cs
  Content.Server/GameTicking/Rules/WizardRuleSystem.cs
  Resources/Audio/Items/Toys/floyd1.ogg
  Resources/Audio/Items/Toys/floyd2.ogg
  Resources/Audio/Items/Toys/floyd3.ogg
  Resources/Locale/en-US/game-ticking/game-presets/preset-wizards.ftl
  Resources/Locale/en-US/store/categories.ftl
  Resources/Locale/en-US/store/currency.ftl
  Resources/Locale/en-US/store/spellbook-catalog.ftl
  Resources/Prototypes/Catalog/spellbook_catalog.yml
  Resources/Prototypes/Entities/Markers/Spawners/Conditional/wizards.yml
  Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/Entities/Mobs/Player/human.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Entities/Objects/Specific/wizard.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/Roles/Antags/wizard.yml
  Resources/Prototypes/Roles/Jobs/Fun/wizard_startinggear.yml
  Resources/Prototypes/SoundCollections/floyd_plush.yml
  Resources/Prototypes/Stacks/Materials/crystals.yml
  Resources/Prototypes/Store/categories.yml
  Resources/Prototypes/Store/currency.yml
  Resources/Prototypes/Store/presets.yml
  Resources/Prototypes/game_presets.yml
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/plushie_floyd.png
Labels: Changes: Sprites
